Scriptname BodycamPresets Native Hidden

; The MCM Save / Load buttons. Bodycam.dll watches the two counters in MCM/Settings/Bodycam.ini
; and does the file work. A counter, not a flag: MCM only writes a setting when its value changes.

; Generated with the MCM files. Begin reads the picked preset in Bodycam.dll and says how many values
; follow; the lines in Load take them in the order of settings.ini.
float Function Begin() native global
float Function Next() native global

Function Bump(string asSetting) global
	MCM.SetModSettingInt("Bodycam", asSetting, MCM.GetModSettingInt("Bodycam", asSetting) + 1)
EndFunction

Function Save() global
	Bump("iSaveTick:Presets")
EndFunction

Function Load() global
	If Begin() as int != 264
		; older plugin or nothing picked: let the plugin write the file
		Bump("iLoadTick:Presets")
		Return
	EndIf
	MCM.SetModSettingBool("Bodycam", "bCrosshairFollow:Main", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bWeaponHold:Main", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bCameraTilt:Main", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bStrafeTilt:Main", Next() > 0.5)
	MCM.SetModSettingInt("Bodycam", "iPreset:Main", Next() as int)
	MCM.SetModSettingBool("Bodycam", "bViewLag:Toggles", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bTurnLean:Toggles", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bGunLean:Toggles", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bCornerPeek:Toggles", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bLookInertia:Toggles", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bGunDrag:Toggles", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bHeadBob:Toggles", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bJumpLand:Toggles", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bStepImpact:Toggles", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bRetract:Toggles", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bFreeAim:Look", Next() > 0.5)
	MCM.SetModSettingInt("Bodycam", "iHipAim:Look", Next() as int)
	MCM.SetModSettingInt("Bodycam", "iHitIndicator:Look", Next() as int)
	MCM.SetModSettingFloat("Bodycam", "fCrosshairScale:Look", Next())
	MCM.SetModSettingFloat("Bodycam", "fFreeAimYawDeg:Look", Next())
	MCM.SetModSettingFloat("Bodycam", "fFreeAimPitchDeg:Look", Next())
	MCM.SetModSettingFloat("Bodycam", "fFreeAimSpeed:Look", Next())
	MCM.SetModSettingFloat("Bodycam", "fViewFloat:Look", Next())
	MCM.SetModSettingFloat("Bodycam", "fFreeAimRecenter:Look", Next())
	MCM.SetModSettingBool("Bodycam", "bFreeAimDrawnOnly:Look", Next() > 0.5)
	MCM.SetModSettingInt("Bodycam", "iPinpoint:Look", Next() as int)
	MCM.SetModSettingFloat("Bodycam", "fRapidFireScatter:Look", Next())
	MCM.SetModSettingFloat("Bodycam", "fLagMaxDeg:Look", Next())
	MCM.SetModSettingFloat("Bodycam", "fLagFreq:Look", Next())
	MCM.SetModSettingFloat("Bodycam", "fLagDamping:Look", Next())
	MCM.SetModSettingFloat("Bodycam", "fBlendRate:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fScoped:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fSightsUpDown:Hold", Next())
	MCM.SetModSettingBool("Bodycam", "bLowReady:Hold", Next() > 0.5)
	MCM.SetModSettingFloat("Bodycam", "fHipFireLevel:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fLowReadyDelay:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fLowReadyRaiseRate:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fLowReadyLowerRate:Hold", Next())
	MCM.SetModSettingBool("Bodycam", "bLowReadyShotRaised:Hold", Next() > 0.5)
	MCM.SetModSettingFloat("Bodycam", "fPistolHipForward:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolHipHeight:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolHipFovOffset:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolHipRaise:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolHipSide:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolHipPitchDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolLowReadyPitchDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolLowReadyYawDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolLowReadyArmShare:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolLowReadyDrop:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolLowReadySide:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolSightsForward:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolSightsRefDist:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolFovOffset:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleHipForward:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleHipHeight:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleHipFovOffset:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleHipRaise:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleHipSide:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleHipPitchDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleLowReadyPitchDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleLowReadyYawDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleLowReadyArmShare:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleLowReadyDrop:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleLowReadySide:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleSightsForward:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleSightsRefDist:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleFovOffset:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunHipForward:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunHipHeight:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunHipFovOffset:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunHipRaise:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunHipSide:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunHipPitchDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunLowReadyPitchDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunLowReadyYawDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunLowReadyArmShare:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunLowReadyDrop:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunLowReadySide:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunSightsForward:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunSightsRefDist:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunFovOffset:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyHipForward:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyHipHeight:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyHipFovOffset:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyHipRaise:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyHipSide:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyHipPitchDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyLowReadyPitchDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyLowReadyYawDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyLowReadyArmShare:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyLowReadyDrop:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyLowReadySide:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavySightsForward:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavySightsRefDist:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyFovOffset:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeHipForward:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeHipHeight:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeHipFovOffset:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeHipRaise:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeHipSide:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeHipPitchDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeLowReadyPitchDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeLowReadyYawDeg:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeLowReadyArmShare:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeLowReadyDrop:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeLowReadySide:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeSightsForward:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeSightsRefDist:Hold", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeFovOffset:Hold", Next())
	MCM.SetModSettingBool("Bodycam", "bEnabled:Recoil", Next() > 0.5)
	MCM.SetModSettingFloat("Bodycam", "fVanillaRecoil:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fAimShare:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fGunKick:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fCameraKick:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fADSScale:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fSpringHz:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fDamping:Recoil", Next())
	MCM.SetModSettingBool("Bodycam", "bAimRecovery:Recoil", Next() > 0.5)
	MCM.SetModSettingFloat("Bodycam", "fAimHz:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fAimDamping:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fCameraHz:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fCameraDamping:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fClimbRetention:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fHorizontal:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fRoll:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolClimbDeg:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleClimbDeg:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fPowerArmor:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fAutoRifleClimbDeg:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunClimbDeg:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyClimbDeg:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fVariation:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fRattle:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fRattleHz:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fRattleDecay:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fPunch:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fPunchHz:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fSettle:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fMaxPitch:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fMaxYaw:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fPistolBack:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fRifleBack:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fShotgunBack:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fHeavyBack:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeClimbDeg:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fMeleeBack:Recoil", Next())
	MCM.SetModSettingFloat("Bodycam", "fSensitivity:Turn", Next())
	MCM.SetModSettingFloat("Bodycam", "fDeadzoneRadS:Turn", Next())
	MCM.SetModSettingFloat("Bodycam", "fCameraTiltDeg:Roll", Next())
	MCM.SetModSettingFloat("Bodycam", "fTiltAlternate:Roll", Next())
	MCM.SetModSettingFloat("Bodycam", "fTiltDriftRate:Roll", Next())
	MCM.SetModSettingFloat("Bodycam", "fTurnDegPerRadS:Roll", Next())
	MCM.SetModSettingFloat("Bodycam", "fMaxDeg:Roll", Next())
	MCM.SetModSettingFloat("Bodycam", "fRate:Roll", Next())
	MCM.SetModSettingFloat("Bodycam", "fReturnRate:Roll", Next())
	MCM.SetModSettingFloat("Bodycam", "fStrafeDeg:Roll", Next())
	MCM.SetModSettingBool("Bodycam", "bNoSideMotion:Bob", Next() > 0.5)
	MCM.SetModSettingFloat("Bodycam", "fRollDeg:Bob", Next())
	MCM.SetModSettingFloat("Bodycam", "fMoveMotion:Bob", Next())
	MCM.SetModSettingFloat("Bodycam", "fBreathAmp:Bob", Next())
	MCM.SetModSettingFloat("Bodycam", "fBreathHz:Bob", Next())
	MCM.SetModSettingFloat("Bodycam", "fStepImpactHz:Bob", Next())
	MCM.SetModSettingFloat("Bodycam", "fStepImpactDecay:Bob", Next())
	MCM.SetModSettingFloat("Bodycam", "fLaunchDip:Jump", Next())
	MCM.SetModSettingFloat("Bodycam", "fLaunchRate:Jump", Next())
	MCM.SetModSettingFloat("Bodycam", "fLandImpact:Jump", Next())
	MCM.SetModSettingFloat("Bodycam", "fLandShakeDeg:Jump", Next())
	MCM.SetModSettingFloat("Bodycam", "fLandCrouch:Jump", Next())
	MCM.SetModSettingFloat("Bodycam", "fLandCrouchRate:Jump", Next())
	MCM.SetModSettingFloat("Bodycam", "fLandGunDip:Jump", Next())
	MCM.SetModSettingFloat("Bodycam", "fLandRefSpeed:Jump", Next())
	MCM.SetModSettingFloat("Bodycam", "fHz:Jump", Next())
	MCM.SetModSettingFloat("Bodycam", "fDecay:Jump", Next())
	MCM.SetModSettingFloat("Bodycam", "fMinAirTime:Jump", Next())
	MCM.SetModSettingFloat("Bodycam", "fTakeoffSpeed:Jump", Next())
	MCM.SetModSettingFloat("Bodycam", "fVertical:BobWalk", Next())
	MCM.SetModSettingFloat("Bodycam", "fLateral:BobWalk", Next())
	MCM.SetModSettingFloat("Bodycam", "fSwayYawDeg:BobWalk", Next())
	MCM.SetModSettingFloat("Bodycam", "fSwayRollDeg:BobWalk", Next())
	MCM.SetModSettingFloat("Bodycam", "fCycleHz:BobWalk", Next())
	MCM.SetModSettingFloat("Bodycam", "fStepImpact:BobWalk", Next())
	MCM.SetModSettingFloat("Bodycam", "fBreathAmp:BobWalk", Next())
	MCM.SetModSettingFloat("Bodycam", "fBreathHz:BobWalk", Next())
	MCM.SetModSettingFloat("Bodycam", "fSpeed:BobWalk", Next())
	MCM.SetModSettingFloat("Bodycam", "fVertical:BobJog", Next())
	MCM.SetModSettingFloat("Bodycam", "fLateral:BobJog", Next())
	MCM.SetModSettingFloat("Bodycam", "fSwayYawDeg:BobJog", Next())
	MCM.SetModSettingFloat("Bodycam", "fSwayRollDeg:BobJog", Next())
	MCM.SetModSettingFloat("Bodycam", "fCycleHz:BobJog", Next())
	MCM.SetModSettingFloat("Bodycam", "fStepImpact:BobJog", Next())
	MCM.SetModSettingFloat("Bodycam", "fBreathAmp:BobJog", Next())
	MCM.SetModSettingFloat("Bodycam", "fBreathHz:BobJog", Next())
	MCM.SetModSettingFloat("Bodycam", "fSpeed:BobJog", Next())
	MCM.SetModSettingFloat("Bodycam", "fVertical:BobSprint", Next())
	MCM.SetModSettingFloat("Bodycam", "fLateral:BobSprint", Next())
	MCM.SetModSettingFloat("Bodycam", "fSwayYawDeg:BobSprint", Next())
	MCM.SetModSettingFloat("Bodycam", "fSwayRollDeg:BobSprint", Next())
	MCM.SetModSettingFloat("Bodycam", "fCycleHz:BobSprint", Next())
	MCM.SetModSettingFloat("Bodycam", "fStepImpact:BobSprint", Next())
	MCM.SetModSettingFloat("Bodycam", "fBreathAmp:BobSprint", Next())
	MCM.SetModSettingFloat("Bodycam", "fBreathHz:BobSprint", Next())
	MCM.SetModSettingFloat("Bodycam", "fSpeed:BobSprint", Next())
	MCM.SetModSettingFloat("Bodycam", "fRestCantDeg:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fRestCantAdsDeg:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fRestPitchDeg:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fCantTurnDegPerRadS:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fCantMaxDeg:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fFollowViewRoll:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fRollMaxDeg:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fCantStrafeDeg:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fCantRate:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fCantDamping:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fLookInertia:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fLookInertiaMax:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fLookInertiaCant:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fLookInertiaSlide:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fLookInertiaRate:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fLookInertiaDamping:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fInertia:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fInertiaMax:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fInertiaRate:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fBobScale:GunMotion", Next())
	MCM.SetModSettingFloat("Bodycam", "fStrafeRefSpeed:GunMotion", Next())
	MCM.SetModSettingInt("Bodycam", "iRigFollowsView:GunMotion", Next() as int)
	MCM.SetModSettingInt("Bodycam", "iRigSpace:GunMotion", Next() as int)
	MCM.SetModSettingInt("Bodycam", "iCameraFollowsRigShift:GunMotion", Next() as int)
	MCM.SetModSettingBool("Bodycam", "bFirstPersonOnly:Stance", Next() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bSuspendInMenus:Stance", Next() > 0.5)
	MCM.SetModSettingFloat("Bodycam", "fPowerArmorScale:Stance", Next())
	MCM.SetModSettingFloat("Bodycam", "fAirborneBobScale:Stance", Next())
	MCM.SetModSettingFloat("Bodycam", "fGroundedProbe:Stance", Next())
	MCM.SetModSettingFloat("Bodycam", "fAirborneFallSpeed:Stance", Next())
	MCM.SetModSettingFloat("Bodycam", "fGroundedRate:Stance", Next())
	MCM.SetModSettingFloat("Bodycam", "fPowerArmorRate:Stance", Next())
	MCM.SetModSettingFloat("Bodycam", "fProbeForward:Detection", Next())
	MCM.SetModSettingFloat("Bodycam", "fPeekDetect:Detection", Next())
	MCM.SetModSettingFloat("Bodycam", "fPeekFull:Detection", Next())
	MCM.SetModSettingFloat("Bodycam", "fPeekStartDeg:Detection", Next())
	MCM.SetModSettingFloat("Bodycam", "fPeekFullDeg:Detection", Next())
	MCM.SetModSettingFloat("Bodycam", "fPeekHipScale:Detection", Next())
	MCM.SetModSettingFloat("Bodycam", "fPeekOverDeg:Detection", Next())
	MCM.SetModSettingFloat("Bodycam", "fPeekMinScale:Detection", Next())
	MCM.SetModSettingFloat("Bodycam", "fSideProbe:Detection", Next())
	MCM.SetModSettingFloat("Bodycam", "fStart:Retract", Next())
	MCM.SetModSettingFloat("Bodycam", "fFull:Retract", Next())
	MCM.SetModSettingFloat("Bodycam", "fBack:Retract", Next())
	MCM.SetModSettingFloat("Bodycam", "fDrop:Retract", Next())
	MCM.SetModSettingFloat("Bodycam", "fPitchDeg:Retract", Next())
	MCM.SetModSettingFloat("Bodycam", "fRate:Retract", Next())
	MCM.SetModSettingFloat("Bodycam", "fPeekDist:CornerGun", Next())
	MCM.SetModSettingFloat("Bodycam", "fYawDeg:CornerGun", Next())
	MCM.SetModSettingFloat("Bodycam", "fCantDeg:CornerGun", Next())
	MCM.SetModSettingFloat("Bodycam", "fRate:CornerGun", Next())
	MCM.SetModSettingFloat("Bodycam", "fDamping:CornerGun", Next())
	MCM.SetModSettingFloat("Bodycam", "fPeekDist:CornerCamera", Next())
	MCM.SetModSettingFloat("Bodycam", "fDrop:CornerCamera", Next())
	MCM.SetModSettingFloat("Bodycam", "fRollDeg:CornerCamera", Next())
	MCM.SetModSettingFloat("Bodycam", "fRate:CornerCamera", Next())
	MCM.SetModSettingFloat("Bodycam", "fReturnRate:CornerCamera", Next())
	MCM.SetModSettingFloat("Bodycam", "fDamping:CornerCamera", Next())
	MCM.SetModSettingFloat("Bodycam", "fMargin:CornerCamera", Next())
	MCM.SetModSettingFloat("Bodycam", "fCant:Signs", Next())
	MCM.SetModSettingFloat("Bodycam", "fYaw:Signs", Next())
	MCM.SetModSettingFloat("Bodycam", "fPitch:Signs", Next())
	MCM.RefreshMenu()
EndFunction
