Scriptname BodycamPresets Native Hidden

; The MCM preset buttons. Bodycam.dll watches the two counters in MCM/Settings/Bodycam.ini
; and does the file work. A counter, not a flag: MCM only writes a setting when its value changes.

; Generated with the MCM files. Begin reads the preset named in the box in Bodycam.dll and says how many values
; follow; the lines in Load take them in the order of settings.ini.
float Function Begin() native global
float Function Value() native global
string Function NextName() native global
string Function PrevName() native global

Function Bump(string asSetting) global
	MCM.SetModSettingInt("Bodycam", asSetting, MCM.GetModSettingInt("Bodycam", asSetting) + 1)
EndFunction

Function Save() global
	Bump("iSaveTick:Presets")
EndFunction

; Previous / Next: the plugin reads the folder and says which preset comes next; MCM's own setter
; puts it in the Preset Name box. "" means the natives are missing or the folder is empty.
Function ShowName(string asName) global
	If asName != ""
		MCM.SetModSettingString("Bodycam", "sName:Presets", asName)
		MCM.RefreshMenu()
	EndIf
EndFunction

Function NextPreset() global
	ShowName(NextName())
EndFunction

Function PrevPreset() global
	ShowName(PrevName())
EndFunction

Function Load() global
	int count = Begin() as int
	If count < 0
		; an earlier press is still being applied
		Return
	EndIf
	If count != 263
		; natives missing or no such preset: let the plugin write the file
		Bump("iLoadTick:Presets")
		Return
	EndIf
	MCM.SetModSettingBool("Bodycam", "bCrosshairFollow:Main", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bWeaponHold:Main", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bCameraTilt:Main", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bStrafeTilt:Main", Value() > 0.5)
	MCM.SetModSettingInt("Bodycam", "iPreset:Main", Value() as int)
	MCM.SetModSettingBool("Bodycam", "bViewLag:Toggles", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bTurnLean:Toggles", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bGunLean:Toggles", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bCornerPeek:Toggles", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bLookInertia:Toggles", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bGunDrag:Toggles", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bHeadBob:Toggles", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bJumpLand:Toggles", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bStepImpact:Toggles", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bRetract:Toggles", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bFreeAim:Look", Value() > 0.5)
	MCM.SetModSettingInt("Bodycam", "iHipAim:Look", Value() as int)
	MCM.SetModSettingInt("Bodycam", "iHitIndicator:Look", Value() as int)
	MCM.SetModSettingFloat("Bodycam", "fCrosshairScale:Look", Value())
	MCM.SetModSettingFloat("Bodycam", "fFreeAimYawDeg:Look", Value())
	MCM.SetModSettingFloat("Bodycam", "fFreeAimPitchDeg:Look", Value())
	MCM.SetModSettingFloat("Bodycam", "fFreeAimSpeed:Look", Value())
	MCM.SetModSettingFloat("Bodycam", "fViewFloat:Look", Value())
	MCM.SetModSettingFloat("Bodycam", "fFreeAimRecenter:Look", Value())
	MCM.SetModSettingBool("Bodycam", "bFreeAimDrawnOnly:Look", Value() > 0.5)
	MCM.SetModSettingInt("Bodycam", "iPinpoint:Look", Value() as int)
	MCM.SetModSettingFloat("Bodycam", "fRapidFireScatter:Look", Value())
	MCM.SetModSettingFloat("Bodycam", "fLagMaxDeg:Look", Value())
	MCM.SetModSettingFloat("Bodycam", "fLagFreq:Look", Value())
	MCM.SetModSettingFloat("Bodycam", "fLagDamping:Look", Value())
	MCM.SetModSettingFloat("Bodycam", "fBlendRate:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fScoped:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fSightsUpDown:Hold", Value())
	MCM.SetModSettingBool("Bodycam", "bLowReady:Hold", Value() > 0.5)
	MCM.SetModSettingFloat("Bodycam", "fHipFireLevel:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fLowReadyDelay:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fLowReadyRaiseRate:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fLowReadyLowerRate:Hold", Value())
	MCM.SetModSettingBool("Bodycam", "bLowReadyShotRaised:Hold", Value() > 0.5)
	MCM.SetModSettingFloat("Bodycam", "fPistolHipForward:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolHipHeight:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolHipFovOffset:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolHipRaise:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolHipSide:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolHipPitchDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolLowReadyPitchDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolLowReadyYawDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolLowReadyArmShare:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolLowReadyDrop:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolLowReadySide:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolSightsForward:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolSightsRefDist:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolFovOffset:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleHipForward:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleHipHeight:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleHipFovOffset:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleHipRaise:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleHipSide:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleHipPitchDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleLowReadyPitchDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleLowReadyYawDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleLowReadyArmShare:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleLowReadyDrop:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleLowReadySide:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleSightsForward:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleSightsRefDist:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleFovOffset:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunHipForward:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunHipHeight:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunHipFovOffset:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunHipRaise:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunHipSide:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunHipPitchDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunLowReadyPitchDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunLowReadyYawDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunLowReadyArmShare:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunLowReadyDrop:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunLowReadySide:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunSightsForward:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunSightsRefDist:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunFovOffset:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyHipForward:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyHipHeight:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyHipFovOffset:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyHipRaise:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyHipSide:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyHipPitchDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyLowReadyPitchDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyLowReadyYawDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyLowReadyArmShare:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyLowReadyDrop:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyLowReadySide:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavySightsForward:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavySightsRefDist:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyFovOffset:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeHipForward:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeHipHeight:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeHipFovOffset:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeHipRaise:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeHipSide:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeHipPitchDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeLowReadyPitchDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeLowReadyYawDeg:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeLowReadyArmShare:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeLowReadyDrop:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeLowReadySide:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeSightsForward:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeSightsRefDist:Hold", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeFovOffset:Hold", Value())
	MCM.SetModSettingBool("Bodycam", "bEnabled:Recoil", Value() > 0.5)
	MCM.SetModSettingFloat("Bodycam", "fVanillaRecoil:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fAimShare:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fGunKick:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fCameraKick:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fADSScale:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fSpringHz:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fDamping:Recoil", Value())
	MCM.SetModSettingBool("Bodycam", "bAimRecovery:Recoil", Value() > 0.5)
	MCM.SetModSettingFloat("Bodycam", "fAimHz:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fAimDamping:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fCameraHz:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fCameraDamping:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fClimbRetention:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fHorizontal:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fRoll:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolClimbDeg:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleClimbDeg:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fPowerArmor:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fAutoRifleClimbDeg:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunClimbDeg:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyClimbDeg:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fVariation:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fRattle:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fRattleHz:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fRattleDecay:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fPunch:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fPunchHz:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fSettle:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fMaxPitch:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fMaxYaw:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fPistolBack:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fRifleBack:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fShotgunBack:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fHeavyBack:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeClimbDeg:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fMeleeBack:Recoil", Value())
	MCM.SetModSettingFloat("Bodycam", "fSensitivity:Turn", Value())
	MCM.SetModSettingFloat("Bodycam", "fDeadzoneRadS:Turn", Value())
	MCM.SetModSettingFloat("Bodycam", "fCameraTiltDeg:Roll", Value())
	MCM.SetModSettingFloat("Bodycam", "fTiltAlternate:Roll", Value())
	MCM.SetModSettingFloat("Bodycam", "fTiltDriftRate:Roll", Value())
	MCM.SetModSettingFloat("Bodycam", "fTurnDegPerRadS:Roll", Value())
	MCM.SetModSettingFloat("Bodycam", "fMaxDeg:Roll", Value())
	MCM.SetModSettingFloat("Bodycam", "fRate:Roll", Value())
	MCM.SetModSettingFloat("Bodycam", "fReturnRate:Roll", Value())
	MCM.SetModSettingFloat("Bodycam", "fStrafeDeg:Roll", Value())
	MCM.SetModSettingBool("Bodycam", "bNoSideMotion:Bob", Value() > 0.5)
	MCM.SetModSettingFloat("Bodycam", "fRollDeg:Bob", Value())
	MCM.SetModSettingFloat("Bodycam", "fMoveMotion:Bob", Value())
	MCM.SetModSettingFloat("Bodycam", "fBreathAmp:Bob", Value())
	MCM.SetModSettingFloat("Bodycam", "fBreathHz:Bob", Value())
	MCM.SetModSettingFloat("Bodycam", "fStepImpactHz:Bob", Value())
	MCM.SetModSettingFloat("Bodycam", "fStepImpactDecay:Bob", Value())
	MCM.SetModSettingFloat("Bodycam", "fLaunchDip:Jump", Value())
	MCM.SetModSettingFloat("Bodycam", "fLaunchRate:Jump", Value())
	MCM.SetModSettingFloat("Bodycam", "fLandImpact:Jump", Value())
	MCM.SetModSettingFloat("Bodycam", "fLandShakeDeg:Jump", Value())
	MCM.SetModSettingFloat("Bodycam", "fLandCrouch:Jump", Value())
	MCM.SetModSettingFloat("Bodycam", "fLandCrouchRate:Jump", Value())
	MCM.SetModSettingFloat("Bodycam", "fLandGunDip:Jump", Value())
	MCM.SetModSettingFloat("Bodycam", "fLandRefSpeed:Jump", Value())
	MCM.SetModSettingFloat("Bodycam", "fHz:Jump", Value())
	MCM.SetModSettingFloat("Bodycam", "fDecay:Jump", Value())
	MCM.SetModSettingFloat("Bodycam", "fMinAirTime:Jump", Value())
	MCM.SetModSettingFloat("Bodycam", "fTakeoffSpeed:Jump", Value())
	MCM.SetModSettingFloat("Bodycam", "fVertical:BobWalk", Value())
	MCM.SetModSettingFloat("Bodycam", "fLateral:BobWalk", Value())
	MCM.SetModSettingFloat("Bodycam", "fSwayYawDeg:BobWalk", Value())
	MCM.SetModSettingFloat("Bodycam", "fSwayRollDeg:BobWalk", Value())
	MCM.SetModSettingFloat("Bodycam", "fCycleHz:BobWalk", Value())
	MCM.SetModSettingFloat("Bodycam", "fStepImpact:BobWalk", Value())
	MCM.SetModSettingFloat("Bodycam", "fBreathAmp:BobWalk", Value())
	MCM.SetModSettingFloat("Bodycam", "fBreathHz:BobWalk", Value())
	MCM.SetModSettingFloat("Bodycam", "fSpeed:BobWalk", Value())
	MCM.SetModSettingFloat("Bodycam", "fVertical:BobJog", Value())
	MCM.SetModSettingFloat("Bodycam", "fLateral:BobJog", Value())
	MCM.SetModSettingFloat("Bodycam", "fSwayYawDeg:BobJog", Value())
	MCM.SetModSettingFloat("Bodycam", "fSwayRollDeg:BobJog", Value())
	MCM.SetModSettingFloat("Bodycam", "fCycleHz:BobJog", Value())
	MCM.SetModSettingFloat("Bodycam", "fStepImpact:BobJog", Value())
	MCM.SetModSettingFloat("Bodycam", "fBreathAmp:BobJog", Value())
	MCM.SetModSettingFloat("Bodycam", "fBreathHz:BobJog", Value())
	MCM.SetModSettingFloat("Bodycam", "fSpeed:BobJog", Value())
	MCM.SetModSettingFloat("Bodycam", "fVertical:BobSprint", Value())
	MCM.SetModSettingFloat("Bodycam", "fLateral:BobSprint", Value())
	MCM.SetModSettingFloat("Bodycam", "fSwayYawDeg:BobSprint", Value())
	MCM.SetModSettingFloat("Bodycam", "fSwayRollDeg:BobSprint", Value())
	MCM.SetModSettingFloat("Bodycam", "fCycleHz:BobSprint", Value())
	MCM.SetModSettingFloat("Bodycam", "fStepImpact:BobSprint", Value())
	MCM.SetModSettingFloat("Bodycam", "fBreathAmp:BobSprint", Value())
	MCM.SetModSettingFloat("Bodycam", "fBreathHz:BobSprint", Value())
	MCM.SetModSettingFloat("Bodycam", "fSpeed:BobSprint", Value())
	MCM.SetModSettingFloat("Bodycam", "fRestCantDeg:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fRestCantAdsDeg:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fRestPitchDeg:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fCantTurnDegPerRadS:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fCantMaxDeg:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fFollowViewRoll:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fRollMaxDeg:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fCantStrafeDeg:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fCantRate:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fCantDamping:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fLookInertia:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fLookInertiaMax:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fLookInertiaRate:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fLookInertiaDamping:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fLookInertiaPush:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fInertia:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fInertiaMax:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fInertiaRate:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fBobScale:GunMotion", Value())
	MCM.SetModSettingFloat("Bodycam", "fStrafeRefSpeed:GunMotion", Value())
	MCM.SetModSettingInt("Bodycam", "iRigFollowsView:GunMotion", Value() as int)
	MCM.SetModSettingInt("Bodycam", "iRigSpace:GunMotion", Value() as int)
	MCM.SetModSettingInt("Bodycam", "iCameraFollowsRigShift:GunMotion", Value() as int)
	MCM.SetModSettingBool("Bodycam", "bFirstPersonOnly:Stance", Value() > 0.5)
	MCM.SetModSettingBool("Bodycam", "bSuspendInMenus:Stance", Value() > 0.5)
	MCM.SetModSettingFloat("Bodycam", "fPowerArmorScale:Stance", Value())
	MCM.SetModSettingFloat("Bodycam", "fAirborneBobScale:Stance", Value())
	MCM.SetModSettingFloat("Bodycam", "fGroundedProbe:Stance", Value())
	MCM.SetModSettingFloat("Bodycam", "fAirborneFallSpeed:Stance", Value())
	MCM.SetModSettingFloat("Bodycam", "fGroundedRate:Stance", Value())
	MCM.SetModSettingFloat("Bodycam", "fPowerArmorRate:Stance", Value())
	MCM.SetModSettingFloat("Bodycam", "fProbeForward:Detection", Value())
	MCM.SetModSettingFloat("Bodycam", "fPeekDetect:Detection", Value())
	MCM.SetModSettingFloat("Bodycam", "fPeekFull:Detection", Value())
	MCM.SetModSettingFloat("Bodycam", "fPeekStartDeg:Detection", Value())
	MCM.SetModSettingFloat("Bodycam", "fPeekFullDeg:Detection", Value())
	MCM.SetModSettingFloat("Bodycam", "fPeekHipScale:Detection", Value())
	MCM.SetModSettingFloat("Bodycam", "fPeekOverDeg:Detection", Value())
	MCM.SetModSettingFloat("Bodycam", "fPeekMinScale:Detection", Value())
	MCM.SetModSettingFloat("Bodycam", "fSideProbe:Detection", Value())
	MCM.SetModSettingFloat("Bodycam", "fStart:Retract", Value())
	MCM.SetModSettingFloat("Bodycam", "fFull:Retract", Value())
	MCM.SetModSettingFloat("Bodycam", "fBack:Retract", Value())
	MCM.SetModSettingFloat("Bodycam", "fDrop:Retract", Value())
	MCM.SetModSettingFloat("Bodycam", "fPitchDeg:Retract", Value())
	MCM.SetModSettingFloat("Bodycam", "fRate:Retract", Value())
	MCM.SetModSettingFloat("Bodycam", "fPeekDist:CornerGun", Value())
	MCM.SetModSettingFloat("Bodycam", "fYawDeg:CornerGun", Value())
	MCM.SetModSettingFloat("Bodycam", "fCantDeg:CornerGun", Value())
	MCM.SetModSettingFloat("Bodycam", "fRate:CornerGun", Value())
	MCM.SetModSettingFloat("Bodycam", "fDamping:CornerGun", Value())
	MCM.SetModSettingFloat("Bodycam", "fPeekDist:CornerCamera", Value())
	MCM.SetModSettingFloat("Bodycam", "fDrop:CornerCamera", Value())
	MCM.SetModSettingFloat("Bodycam", "fRollDeg:CornerCamera", Value())
	MCM.SetModSettingFloat("Bodycam", "fRate:CornerCamera", Value())
	MCM.SetModSettingFloat("Bodycam", "fReturnRate:CornerCamera", Value())
	MCM.SetModSettingFloat("Bodycam", "fDamping:CornerCamera", Value())
	MCM.SetModSettingFloat("Bodycam", "fMargin:CornerCamera", Value())
	MCM.SetModSettingFloat("Bodycam", "fCant:Signs", Value())
	MCM.SetModSettingFloat("Bodycam", "fYaw:Signs", Value())
	MCM.SetModSettingFloat("Bodycam", "fPitch:Signs", Value())
	MCM.RefreshMenu()
EndFunction
